POST http://localhost:8080/event
Content-Type: application/json
Authorization: JWT_TOKEN_GOES_HERE

{
	"name": "Sample Event 1",
	"description": "This is a sample event.",
	"location": "Online",
	"date_time": "2023-10-10T10:00:00Z"
}